# Generated by Django 4.2.10 on 2024-04-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='discount_percent',
            field=models.IntegerField(default=0.0),
        ),
    ]
