# Generated by Django 4.2.10 on 2024-04-03 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0005_appliedcouponcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcouponcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
