# Generated by Django 5.0.2 on 2024-03-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_combo_delete_adddata_delete_addproduct_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='combo_img',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
