# Generated by Django 5.0.2 on 2024-04-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_remove_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
