# Generated by Django 5.0.2 on 2024-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_alter_product_skin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='skin_type',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
