# Generated by Django 5.0.2 on 2024-04-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0017_remove_product_skin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
