# Generated by Django 5.0.1 on 2024-04-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_productrating'),
        ('testing', '0018_alter_product_description'),
    ]

    operations = [
    ]
