# Generated by Django 5.0.2 on 2024-04-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0019_merge_20240418_1359'),
        ('testing', '0019_merge_20240418_1402'),
    ]

    operations = [
    ]
