# Generated by Django 4.2.10 on 2024-04-02 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0010_combo_combo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('purchased', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to='testing.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=30, null=True)),
                ('order_id', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_method', models.CharField(choices=[('Cash_On_Delivery', 'Cash On Delivery'), ('SSLCommerz', 'SSLCommerz')], default='Cash_On_Delivery', max_length=30)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_product', models.ManyToManyField(to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
