# Generated by Django 4.2.10 on 2024-04-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_coupon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash_On_Delivery', 'Cash On Delivery')], default='Cash_On_Delivery', max_length=30),
        ),
    ]
